export default {
  install(Vue) {
    registerVueComponent(
      'ecom-cart',
      require('./Cart/Component.vue').default,
      Vue,
      'ecom-vue-components/src/Cart/Component.vue'
    );
    registerVueComponent(
      'ecom-contact-form',
      require('./ContactPage/ContactForm/Component.vue').default,
      Vue,
      'ecom-vue-components/src/ContactPage/ContactForm/Component.vue'
    );
    registerVueComponent(
      'ecom-footer',
      require('./Footer/Component.vue').default,
      Vue,
      'ecom-vue-components/src/Footer/Component.vue'
    );
    registerVueComponent(
      'ecom-header',
      require('./Header/Component.vue').default,
      Vue,
      'ecom-vue-components/src/Header/Component.vue'
    );
    registerVueComponent(
      'ecom-homepage-about-us',
      require('./HomePage/AboutUs/Component.vue').default,
      Vue,
      'ecom-vue-components/src/HomePage/AboutUs/Component.vue'
    );
    registerVueComponent(
      'ecom-homepage-carousel',
      require('./HomePage/Carousel/Component.vue').default,
      Vue,
      'ecom-vue-components/src/HomePage/Carousel/Component.vue'
    );
    registerVueComponent(
      'ecom-homepage-content',
      require('./HomePage/Content/Component.vue').default,
      Vue,
      'ecom-vue-components/src/HomePage/Content/Component.vue'
    );
    registerVueComponent(
      'ecom-info',
      require('./Info/Component.vue').default,
      Vue,
      'ecom-vue-components/src/Info/Component.vue'
    );
    registerVueComponent(
      'ecom-info-page-info-box',
      require('./InfoPage/InfoBox/Component.vue').default,
      Vue,
      'ecom-vue-components/src/InfoPage/InfoBox/Component.vue'
    );
    registerVueComponent(
      'ecom-info-page-info-breadcrumb',
      require('./InfoPage/InfoBreadcrumb/Component.vue').default,
      Vue,
      'ecom-vue-components/src/InfoPage/InfoBreadcrumb/Component.vue'
    );
    registerVueComponent(
      'ecom-info-page-info-text',
      require('./InfoPage/InfoText/Component.vue').default,
      Vue,
      'ecom-vue-components/src/InfoPage/InfoText/Component.vue'
    );
    registerVueComponent(
      'ecom-newsletter',
      require('./Newsletter/Component.vue').default,
      Vue,
      'ecom-vue-components/src/Newsletter/Component.vue'
    );
    registerVueComponent(
      'ecom-products-page-breadc',
      require('./ProductsPage/Breadc/Component.vue').default,
      Vue,
      'ecom-vue-components/src/ProductsPage/Breadc/Component.vue'
    );
    registerVueComponent(
      'ecom-products-page-card',
      require('./ProductsPage/Card/Component.vue').default,
      Vue,
      'ecom-vue-components/src/ProductsPage/Card/Component.vue'
    );
    registerVueComponent(
      'ecom-products-page-grid',
      require('./ProductsPage/Grid/Component.vue').default,
      Vue,
      'ecom-vue-components/src/ProductsPage/Grid/Component.vue'
    );
    registerVueComponent(
      'ecom-products-page-slider',
      require('./ProductsPage/slider/Component.vue').default,
      Vue,
      'ecom-vue-components/src/ProductsPage/slider/Component.vue'
    );
  },
};
